(ns kouta-indeksoija-service.scheduled.scheduled-jobs-test
  (:require [clojure.test :refer :all]
            [mount.core :as mount]
            [kouta-indeksoija-service.scheduled.jobs :as jobs]
            [kouta-indeksoija-service.util.conf :refer [env]]))

(deftest scheduled-jobs-test
  (mount/start)
  (let [sqs-called (atom false)
        que-called (atom false)
        notification-called (atom false)]
    (with-redefs [env {:lokalisaatio-indexing-cron-string "* 0/30 * ? * *"
                       :organisaatio-indexing-cron-string "* 0 * ? * *"
                       :osaamismerkki-indexing-cron-string "* 0/5 * ? * *"
                       :queueing-cron-string "*/1 * * ? * *"}
                  kouta-indeksoija-service.queue.queue/index-from-sqs (fn [] (do (reset! sqs-called true) (loop [] (recur))))
                  kouta-indeksoija-service.scheduled.jobs/handle-and-queue-changed-data (fn [] (reset! que-called true))
                  kouta-indeksoija-service.queue.notification-queue/read-and-send-notifications (fn [] (do (reset! notification-called true) (loop [] (recur))))]

    (testing "Jobs should"
      (testing "schedule all jobs"
        (is (= 0 (count (jobs/get-jobs-info))))
        (jobs/schedule-jobs)
        (is (= 6 (count (jobs/get-jobs-info)))))

      (testing "reset all jobs"
        (is (= 6 (count (jobs/get-jobs-info))))
        (jobs/reset-jobs)
        (is (= 0 (count (jobs/get-jobs-info))))))

      (testing "pause and resume jobs"
        (jobs/schedule-jobs)
        (let [job-state (fn [name] (first (map :state (:triggers (first (filter #(= (str "DEFAULT.jobs." name ) (:job %)) (jobs/get-jobs-info)))))))]
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/osaamismerkki-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/pause-sqs-job)
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/osaamismerkki-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/pause-notification-job)
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/osaamismerkki-indexing-job-name)))
          (jobs/pause-queueing-job)
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/pause-lokalisaatio-indexing-job)
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/pause-organisaatio-indexing-job)
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/resume-sqs-job)
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "PAUSED" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/resume-notification-job)
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "PAUSED" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/resume-queueing-job)
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "PAUSED" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/resume-lokalisaatio-indexing-job)
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "PAUSED" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/resume-organisaatio-indexing-job)
          (is (= "NORMAL" (job-state jobs/sqs-job-name)))
          (is (= "NORMAL" (job-state jobs/notification-job-name)))
          (is (= "NORMAL" (job-state jobs/queueing-job-name)))
          (is (= "NORMAL" (job-state jobs/lokalisaatio-indexing-job-name)))
          (is (= "NORMAL" (job-state jobs/organisaatio-indexing-job-name)))
          (jobs/reset-jobs))))))
